############################################################################
# List files in the current directory using the in-built command module
############################################################################
---
- name: List files
  hosts: machines
  # connection: local
  gather_facts: false
  tasks:
    - name: "List files in the current directory"
      ansible.builtin.command: "ls"
      register: output # <- Registers the command output.
      changed_when: output.rc != 0 # <- Uses the return code to define when the task has changed.