# code: language=ansible
############################################################################
# Change the OS user password without installing passlib
############################################################################
---
- name: Change OS user password without installing passlib
  hosts: all
  gather_facts: false
  tasks:
    - name: "Change os user password"
      ansible.builtin.raw: echo -e "{{ NEW_PASSWORD }}\n{{ NEW_PASSWORD }}" | passwd {{ USER }}
      changed_when: false
      become: true # <== become root user on Linux to change the passwd for other users
